---
- name: Delete users
  hosts: server
  gather_facts: yes
  become: yes
  become_method: sudo

  vars_files:
   - NIR-users_data.yml

  tasks:

  - name: Delete user files of {{ item.username }} on server
    file: 
      path: /home/{{ item.username }}
      state: absent
    loop: "{{ users }}"

  - name: Delete user {{ item.username }} on server
    user:
      name: "{{ item.username }}"
      state: absent
    loop: "{{ users }}"